framework:
    http_client:
        scoped_clients:
            omdb.api.client:
                base_uri: 'http://www.omdbapi.com'
                query:
                    apikey: '%env(OMDB_API_KEY)%'
